version: '3.8'
services:
  my-java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_URL=jdbc:postgresql://my-postgres:5432/mydb
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - my-postgres
    networks:
      - my-network

  my-postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi.yml:/openapi/openapi.yml
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
